defaults:
  - _self_ # with self here, repeated entries outside take preference
  - dataset: entsoe_15min_prognose
  - loss: distribution
  - model_params: nhits
  - params: params
  - paths: project_pahts
  - logger: comet
