# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

h: 96 # one day
name: "entsoe-15min"
freq: "15min"
comet_project: ${dataset.name}
comet_workspace: "tms"
datasets_main_dir: "/mnt/data/oe215/rhindrikson/datasets/load"

# dataset_dir: ${dataset.datasets_main_dir}/${dataset.name}
dataset_dir: "/mnt/data/oe215/rhindrikson/datasets/load/entsoe-15min/example-processed-data"

data: ${dataset.dataset_dir}/data.csv
futr: ""
