# NHiTS Hyperparameter Search Space Configuration

# Fixed parameters
start_padding_enabled: true
n_blocks: 5
mlp_units: 
  - n: 5
  - shape: [64, 64]
scaler_type: "robust"

max_steps: [500, 1000]

# Tunable parameters for Optuna

input_size: [24, 48, 72]

n_pool_kernel_size:
  - [1, 1, 1, 1, 1]
  - [2, 2, 2, 2, 2]
  - [4, 4, 4, 4, 4]
  - [8, 4, 2, 1, 1]

n_freq_downsample:
  - [8, 4, 2, 1, 1]
  - [1, 1, 1, 1, 1]

learning_rate:
  type: float
  low: 0.0001
  high: 0.01
  log: true

batch_size: [1, 4, 10]

windows_batch_size: [128, 256, 512]

random_seed:
  type: int
  low: 1
  high: 20

activation: ["ReLU"]

interpolation_mode: ["linear"]

val_check_steps: [100]
