_target_: comet_ml.Experiment

auto_log: false
auto_param_logging: false
auto_metric_logging: false
auto_metric_step_rate: 100
auto_histogram_epoch_rate: 1
auto_histogram_weight_logging: false
auto_histogram_gradient_logging: false
auto_histogram_activation_logging: false
auto_log_co2: false
log_env_details: false
log_env_gpu: false
log_env_cpu: false
log_env_network: false
log_env_disk: false
log_env_host: false
log_git_patch: false
display_summary_level: 0
